# fly.toml app configuration file generated for passport-client on 2024-01-15T00:48:26+06:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "passport-client"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.3"

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  DB_CONNECTION = "pgsql"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "file"
  # SESSION_SECURE_COOKIE = "true"
  # API_URL="https://passport-server.fly.dev"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024


[mounts]
  source="storage_vol"
  destination="/var/www/html/storage"

